name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code dans github
        uses: actions/checkout@v4

      - name: Installation des dépendances
        working-directory: ./frontend
        run: npm install

      - name: Installation de chrome
        run: sudo apt upgrade google-chrome-stable

      - name: Lancement de la commande test de angular
        run: npm run test

      - name: build du frontend
        run: npm run build


  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code dans github
        uses: actions/checkout@v4

      - name: Installation des dependences
        working-directory: first-api
        run: npm




